### ISSUE TITLE
Setup CI with travis and make a first release

### ISSUE THREAD

**Issue by fkolar** [ngx-meta/rules#1]
Setup TRAVIS CI for this new project to make sure all the check-in are validated along with other tasks:

* Prepare a release scripts to make npm publish easy and automated. 
* Also let's create first release to the NPM repo.  

#### The plan is to slowly remove all the packages so only metaui stays, but for now we need to keep all this for compatibility reasons

What is the good practice now? I see projects to be compatible with NG they kind of follow the same 6.1.x version and some ignore this and make their own 0.x.x

Which one to pick?

**Comment by zackarychapple** [comment]
It would be good to release ngx-meta as a single versioned package. Unless you see people only pulling in core, components, ui independently.  Even with that, we have tree shaking so it makes sense to have it all in one.  Lets follow more of the rxjs model where everything is in one versioned dependency.

**Comment by fkolar** [comment]
In our case I dont really want people to pull separe packages, this is something they can do in the other repo. 

so it make sense to have only @ng-meta/rules, where as we go we will start pull it out things so only metaui is left

**Comment by zackarychapple** [comment]
As per our offline discussion it would possibly be better to just have rules as a directory and an import within the `@ngx-meta` package

**Comment by fkolar** [comment]
Created scripts for releasing and publishing. For now we do publish under `@ngx-metaui`  as `@ngx-meta` org is taken.

**Comment by fkolar** [comment]
CI travis should be UP + added badges into the README.md
