### ISSUE TITLE
Remove npmInstall option from ng-add schematics

### ISSUE THREAD

**Issue by fkolar** [ngx-meta/rules#47]
<!
## I'm submitting a...
[ X] Bug report  
[X ] Documentation issue or request
## Current behavior

@GregOnNet 

## Expected behavior
Remove unnessesary option from the ng-add schematics `npmInstall` as not everybody uses npm and some use yarn. This way it might confuse developers.

**Comment by GregOnNet** [comment]
If you like I can provide a PR for it.

**Comment by fkolar** [comment]
> If you like I can provide a PR for it.
Definitelly.
