### ISSUE TITLE
Review and correct metaUI architecture document explaining basics of MetaUI

### ISSUE THREAD

**Issue by fkolar** [ngx-meta/rules#5]
There is a document under the https://github.com/ngx-meta/rules/blob/master/packages/metaui/docs/architecture.md and it need somebody to look it over to see if it makes some sense

Plus /Readme.md

**Comment by zackarychapple** [comment]
There were some questions from a discussion I was having around meta and how to interact with meta on the server itself.  If we think about it, `meta ui` is actually only the visual representation of a larger need of extensibility.  If I make a field required for some customers but not required for others based on my roles in meta, how do I then go and verify that on my node server, how do I verify it on my api gateway, how do I drive error messages for it?  These are some of the reasons we have to consider how we extract meta core.

**Comment by fkolar** [comment]
Readme updated by @realhan, now the other docs  - thanks
